name: tests

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2, 8.3, 8.4]
        laravel: [10, 11, 12, 13]
        include:
          - php: 8.2
            laravel: 9
          - php: 8.1
            laravel: 9
          - php: '8.0'
            laravel: 9
        exclude:
          - php: 8.5
            laravel: 10
          - php: 8.5
            laravel: 11
          - php: 8.4
            laravel: 10
          - php: 8.2
            laravel: 13
          - php: 8.1
            laravel: 11
          - php: 8.1
            laravel: 12
          - php: 8.1
            laravel: 13

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction --no-progress --with="illuminate/contracts:^${{ matrix.laravel }}"

      - name: Execute tests
        run: vendor/bin/phpunit

  tests-using-meilisearch:
    runs-on: ubuntu-22.04

    services:
      meilisearch:
        image: getmeili/meilisearch:latest
        ports:
          - 7700:7700
        env:
          MEILI_MASTER_KEY: masterKey
          MEILI_NO_ANALYTICS: true

    strategy:
      fail-fast: true
      matrix:
        php: ['8.0', 8.1, 8.2, 8.3, 8.4]

    name: PHP ${{ matrix.php }} using Meilisearch

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
           composer update --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit --no-configuration --no-coverage --color --bootstrap vendor/autoload.php --group meilisearch tests/Integration
        env:
          MEILISEARCH_HOST: "http://localhost:7700"
          MEILISEARCH_KEY: 'masterKey'
          DB_CONNECTION: 'testing'

  tests-using-typesense:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
          php: ['8.0', 8.1, 8.2, 8.3, 8.4]

    name: PHP ${{ matrix.php }} using Typesense

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Start Typesense
        uses: jirevwe/typesense-github-action@v1.0.1
        with:
          typesense-version: 30.1
          typesense-api-key: masterKey

      - name: Curl Typesense
        run: sleep 10 && curl http://localhost:8108/health

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit --no-configuration --no-coverage --color --bootstrap vendor/autoload.php --group typesense tests/Integration
        env:
          TYPESENSE_HOST: 'localhost'
          TYPESENSE_PORT: 8108
          TYPESENSE_API_KEY: 'masterKey'
          DB_CONNECTION: 'testing'
