name: "Update Changelog"

on:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  update:
    permissions:
      contents: none
    uses: laravel/.github/.github/workflows/update-changelog.yml@main
